services:
  db:
    image: postgres:16
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: "pg_isready"

  web: 
    build: .
    command:  >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata db_inmobiliaria.json &&
             gunicorn inmobiliaria.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80

    depends_on:
      - web

volumes:
  postgres_data:
